name: goal_quest
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`.

dependencies:
  android_alarm_manager_plus: ^2.1.0
  animated_splash_screen: ^1.3.0
  animated_text_kit: ^4.2.2
  awesome_notifications: ^0.7.4+1
 
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  expandable: ^5.0.1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  google_fonts: ^4.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.17.0

dev_dependencies:
  build_runner: ^2.3.3
  flutter_launcher_icons: "^0.11.0"
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.0

flutter_test:
  sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  background_color: '#CF6F19'
  image_path: "assets/icon/round_logo.png"
  adaptive_icon_foreground: "assets/icon/round_logo.png"
  adaptive_icon_background: '#CF6F19' 
  min_sdk_android: 21


# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/

  
